repos:
  - repo: local
    hooks:
      - entry: poetry run isort .
        id: isort
        language: system
        name: isort
        types:
          - python
      - entry: poetry run black .
        id: black
        language: system
        name: black
        types:
          - python
      - entry: poetry run flake8 .
        id: flake8
        language: system
        name: flake8
        types:
          - python
  - repo: local
    hooks:
      - id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
