name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Set up Poetry
        uses: abatilo/actions-poetry@master
        with:
          poetry-version: 1.1.12
      - name: Install dependencies
        run: |
          python -m pip install nox
      - name: Test with nox
        run: |
          nox -rs ci
