name: Deploy GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Set up Poetry
        uses: abatilo/actions-poetry@master
        with:
          poetry-version: 1.1.12
      - name: Install dependencies
        run: |
          poetry install
      - name: Test with nox
        run: |
          nox -rs docs_github_pages
